version: '3'
services:
     frontend_deploy:
         image: "manishadsilva/$IMAGE:$BUILD_TAG"
         container_name: frontend
         ports:
              - "4200:4200"
         networks:
              - net 
networks:
        net:

